# SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company
#
# SPDX-License-Identifier: Apache-2.0

version: 2

builds:
  - main: ./main.go
    binary: ./bin/helm-charts-plugin
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64

archives:
  - format: tar.gz
    files:
      - LICENSE
      - plugin.yaml
