# SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company
#
# SPDX-License-Identifier: Apache-2.0

name: "charts"
version: "1.1.6"
usage: "Manage Helm charts."
description: "This plugin helps to manage helm charts."
command: "$HELM_PLUGIN_DIR/bin/helm-charts"
useTunnel: false
hooks:
  install: "cd $HELM_PLUGIN_DIR; scripts/install_plugin.sh"
  update: "cd $HELM_PLUGIN_DIR; scripts/install_plugin.sh"
