name: "charts"
version: "1.0.4"
usage: "Manage Helm charts."
description: "This plugin helps to manage helm charts."
command: "$HELM_PLUGIN_DIR/bin/helm-charts"
useTunnel: false
hooks:
  install: "cd $HELM_PLUGIN_DIR; scripts/install_plugin.sh"
  update: "cd $HELM_PLUGIN_DIR; scripts/install_plugin.sh"
